//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Education manage system.rc
//
#define IDC_MYICON                      2
#define IDD_EDUCATIONMANAGESYSTEM_DIALOG 102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDS_APP_TITLE_ADMIN             103
#define IDM_ABOUT                       104
#define IDS_APP_TITLE_TEACHER           104
#define IDM_EXIT                        105
#define IDS_APP_TITLE_STUDENT           105
#define IDS_HELLO                       106
#define IDI_EDUCATIONMANAGESYSTEM       107
#define IDI_SMALL                       108
#define IDC_EDUCATIONMANAGESYSTEM       109
#define IDS_EDUCATIONMANAGESYSTEM       110
#define IDR_MAINFRAME                   128
#define IDR_MENU_STUDENT                129
#define IDR_MENU_TEACHER                130
#define IDR_MENU_ADMIN                  131
#define IDD_LOADING                     132
#define IDD_a_account_inquire           140
#define IDD_a_self_info                 142
#define IDD_a_account_modification1     143
#define IDD_a_account_modification      143
#define IDD_a_college_inquire           145
#define IDD_a_self_check                146
#define IDD_a_self_password             150
#define IDB_BITMAP2                     155
#define IDB_BITMAP1                     156
#define IDD_a_college_modification      157
#define IDD_a_profession_inquire        158
#define IDD_a_profession_modification   159
#define IDD_a_course_inquire            160
#define IDD_a_course_modification       161
#define IDD_a_class_inquire             162
#define IDD_a_class_modification        163
#define IDD_a_teacher_inquire           164
#define IDB_BITMAP3                     165
#define IDD_a_teacher_modification      165
#define IDD_a_student_inquire           166
#define IDI_lightfocus                  167
#define IDD_a_student_modification      167
#define IDI_lightfocussmall             168
#define IDD_a_score_inquire             175
#define IDD_a_score_modification        176
#define IDD_a_score_self_inquire        177
#define IDD_a_score_term_inquire        178
#define IDD_a_score_enter               179
#define IDD_a_score_analyse_average     181
#define IDD_a_score_analyse_sum         182
#define IDC_LOADING_USER                1000
#define IDC_LOADING_PASSWORD            1001
#define IDC_LOADING_ENTER               1002
#define IDC_LOADING_EXIT                1003
#define IDC_BUTTON_a_                   1004
#define BUTTON_a_self_info_enter        1004
#define IDC_BUTTON2                     1005
#define BUTTON_a_self_info_affirm       1005
#define BUTTON_a_college_modification_affirm 1005
#define BUTTON_a_profession_inquire_top 1005
#define BUTTON_a_profession_modification_add 1005
#define BUTTON_a_course_inquire_prior   1005
#define BUTTON_a_course_modification_add 1005
#define BUTTON_a_class_inquire_prior    1005
#define BUTTON_a_class_modification_add 1005
#define BUTTON_a_account_inquire_prior  1005
#define BUTTON_a_account_modification_add 1005
#define BUTTON_a_score_modification_prior 1005
#define BUTTON_a_score_enter_prior      1005
#define IDC_BUTTON3                     1006
#define BUTTON_a_self_info_exit         1006
#define BUTTON_a_college_modification_add 1006
#define BUTTON_a_profession_inquire_prior 1006
#define BUTTON_a_profession_modification_affirm 1006
#define BUTTON_a_course_inquire_next    1006
#define BUTTON_a_course_modification_affirm 1006
#define BUTTON_a_class_inquire_next     1006
#define BUTTON_a_class_modification_affirm 1006
#define BUTTON_a_account_inquire_next   1006
#define BUTTON_a_score_modification_next 1006
#define BUTTON_a_score_enter_next       1006
#define BUTTON_a_account_inquire_exit   1007
#define BUTTON_a_profession_inquire_next 1007
#define EDIT_a_self_info_id             1008
#define BUTTON_a_profession_inquire_exit 1008
#define EDIT_a_self_info_name           1009
#define EDIT_a_self_info_sex            1010
#define EDIT_a_self_info_nation         1011
#define EDIT_a_self_info_face           1012
#define EDIT_a_self_info_birth          1013
#define EDIT_a_self_info_time           1014
#define BUTTON_a_self_info_revocation   1020
#define BUTTON_a_account_modification_revocation 1021
#define BUTTON_a_account_modification_exit 1022
#define EDIT_a_account_inquire_id       1023
#define EDIT_a_account_inquire_id1      1023
#define EDIT_a_account_inquire_name     1024
#define EDIT_a_account_inquire_id2      1024
#define EDIT_a_account_inquire_sex      1025
#define EDIT_a_account_inquire_id3      1025
#define EDIT_a_account_inquire_nation   1026
#define EDIT_a_account_inquire_id4      1026
#define EDIT_a_account_inquire_face     1027
#define EDIT_a_account_inquire_id5      1027
#define EDIT_a_account_inquire_birth    1028
#define EDIT_a_account_inquire_id6      1028
#define BUTTON_a_account_inquire_enter  1029
#define EDIT_a_account_modification_id  1030
#define EDIT_a_account_modification_name 1031
#define BUTTON_a_account_modification_enter 1036
#define BUTTON_a_account_modification_affirm 1037
#define COMBO_a_account_modification_sex 1038
#define COMBO_a_account_modification_face 1039
#define COMBO_a_self_nation             1040
#define COMBO_a_self_sex                1043
#define COMBO_a_self_face               1044
#define COMBO_a_self_birth_y            1046
#define COMBO_a_account_modification_nation 1047
#define COMBO_a_self_birth_m            1047
#define COMBO_a_account_modification_birth_y 1048
#define COMBO_a_self_birth_d            1048
#define COMBO_a_account_modification_birth_m 1049
#define COMBO_a_account_modification_birth_d 1050
#define IDC_DATETIMEPICKER1             1057
#define EDIT_a_self_info_unit           1068
#define EDIT_a_self_info_college        1068
#define EDIT_a_self_info_profession     1069
#define EDIT_a_self_info_identity       1071
#define EDIT_a_self_password_old        1080
#define EDIT_a_self_password_new1       1081
#define EDIT_a_self_password_new2       1082
#define BUTTON_a_self_password_affirm   1083
#define BUTTON_a_self_password_cancel   1084
#define EDIT_a_college_inquire_id1      1114
#define EDIT_a_college_inquire_name1    1115
#define EDIT_a_college_inquire_id2      1116
#define EDIT_a_college_inquire_id3      1117
#define EDIT_a_college_inquire_id4      1118
#define EDIT_a_college_inquire_id5      1119
#define EDIT_a_college_inquire_id6      1120
#define BUTTON_a_college_inquire_top    1121
#define BUTTON_a_college_inquire_prior  1122
#define EDIT_a_college_inquire_name2    1123
#define EDIT_a_college_inquire_name3    1124
#define EDIT_a_college_inquire_name4    1125
#define EDIT_a_college_inquire_name5    1126
#define EDIT_a_college_inquire_name6    1127
#define BUTTON_a_college_inquire_next   1128
#define BUTTON_a_college_inquire_exit   1129
#define EDIT_a_college_inquire_page     1130
#define EDIT_a_college_modification_oldid 1131
#define BUTTON_a_college_modification_location 1132
#define EDIT_a_college_modification_oldid1 1133
#define EDIT_a_college_modification_oldname 1134
#define EDIT_a_college_modification_newid 1135
#define EDIT_a_college_modification_newname 1136
#define BUTTON_a_college_modification_delete 1137
#define BUTTON_a_college_modification_exit 1138
#define EDIT_a_profession_inquire_id1   1140
#define EDIT_a_profession_inquire_id2   1147
#define EDIT_a_profession_inquire_id3   1148
#define EDIT_a_profession_inquire_id4   1149
#define EDIT_a_profession_inquire_id5   1150
#define EDIT_a_profession_inquire_id6   1151
#define EDIT_a_profession_inquire_name1 1152
#define EDIT_a_profession_inquire_name2 1153
#define EDIT_a_profession_inquire_name3 1154
#define EDIT_a_profession_inquire_name4 1155
#define EDIT_a_profession_inquire_name5 1156
#define EDIT_a_profession_inquire_name6 1157
#define EDIT_a_profession_inquire_college1 1158
#define EDIT_a_profession_inquire_college2 1159
#define EDIT_a_profession_inquire_college3 1160
#define EDIT_a_profession_inquire_college4 1161
#define EDIT_a_profession_inquire_college5 1162
#define EDIT_a_profession_inquire_college6 1163
#define EDIT_a_profession_inquire_page  1165
#define EDIT_a_profession_modification_oldid 1166
#define EDIT_a_profession_modification_oldid1 1167
#define EDIT_a_profession_modification_oldname 1168
#define EDIT_a_profession_modification_oldcollege 1169
#define EDIT_a_profession_modification_newid 1170
#define EDIT_a_profession_modification_newname 1171
#define EDIT_a_profession_modification_newcollege 1172
#define BUTTON_a_profession_modification_location 1173
#define BUTTON_a_profession_modification_delete 1174
#define BUTTON_a_profession_modification_exit 1175
#define EDIT_a_course_inquire_id1       1176
#define EDIT_a_course_inquire_id2       1177
#define EDIT_a_course_inquire_id3       1178
#define EDIT_a_course_inquire_id4       1179
#define EDIT_a_course_inquire_id5       1180
#define EDIT_a_course_inquire_id6       1181
#define EDIT_a_course_inquire_name1     1182
#define EDIT_a_course_inquire_name2     1183
#define EDIT_a_course_inquire_name3     1184
#define EDIT_a_course_inquire_name4     1185
#define EDIT_a_course_inquire_name5     1186
#define EDIT_a_course_inquire_name6     1187
#define EDIT_a_course_inquire_page      1188
#define BUTTON_a_course_inquire_top     1189
#define BUTTON_a_course_inquire_exit    1190
#define EDIT_a_course_modification_oldid 1191
#define EDIT_a_course_modification_oldid1 1192
#define EDIT_a_course_modification_oldname 1193
#define EDIT_a_course_modification_newid 1194
#define EDIT_a_course_modification_newname 1195
#define BUTTON_a_course_modification_location 1196
#define BUTTON_a_course_modification_delete 1197
#define BUTTON_a_course_modification_exit 1198
#define EDIT_a_class_inquire_id1        1199
#define EDIT_a_class_inquire_name1      1200
#define EDIT_a_class_inquire_profession1 1201
#define EDIT_a_class_inquire_college1   1202
#define EDIT_a_class_inquire_id2        1203
#define EDIT_a_class_inquire_name2      1204
#define EDIT_a_class_inquire_profession2 1205
#define EDIT_a_class_inquire_college2   1206
#define EDIT_a_class_inquire_id3        1207
#define EDIT_a_class_inquire_name3      1208
#define EDIT_a_class_inquire_profession3 1209
#define EDIT_a_class_inquire_college3   1210
#define EDIT_a_class_inquire_id4        1211
#define EDIT_a_class_inquire_name4      1212
#define EDIT_a_class_inquire_profession4 1213
#define EDIT_a_class_inquire_college4   1214
#define EDIT_a_class_inquire_id5        1215
#define EDIT_a_class_inquire_name5      1216
#define EDIT_a_class_inquire_profession5 1217
#define EDIT_a_class_inquire_college5   1218
#define EDIT_a_class_inquire_id6        1219
#define EDIT_a_class_inquire_name6      1220
#define EDIT_a_class_inquire_profession6 1221
#define EDIT_a_class_inquire_college6   1222
#define EDIT_a_class_inquire_page       1223
#define BUTTON_a_class_inquire_top      1224
#define BUTTON_a_class_inquire_exit     1225
#define EDIT_a_class_modification_oldid 1226
#define EDIT_a_class_modification_oldid1 1227
#define EDIT_a_class_modification_oldname 1228
#define EDIT_a_class_modification_oldprofession 1229
#define EDIT_a_class_modification_oldcollege 1230
#define EDIT_a_class_modification_newid 1231
#define EDIT_a_class_modification_newname 1232
#define EDIT_a_class_modification_newprofession 1233
#define EDIT_a_class_modification_newcollege 1234
#define BUTTON_a_class_modification_location 1235
#define BUTTON_a_class_modification_delete 1236
#define BUTTON_a_class_modification_exit 1237
#define EDIT_a_account_inquire_name1    1239
#define EDIT_a_account_inquire_sex1     1240
#define EDIT_a_account_inquire_face1    1242
#define EDIT_a_account_inquire_unit1    1245
#define EDIT_a_account_inquire_college1 1245
#define EDIT_a_account_inquire_profession1 1246
#define EDIT_a_account_inquire_grade1   1247
#define EDIT_a_account_inquire_name2    1248
#define EDIT_a_account_inquire_sex2     1249
#define EDIT_a_account_inquire_page     1250
#define EDIT_a_account_inquire_face2    1251
#define BUTTON_a_account_inquire_top    1252
#define EDIT_a_account_inquire_unit2    1254
#define EDIT_a_account_inquire_college2 1254
#define EDIT_a_account_modification_oldid 1254
#define EDIT_a_account_inquire_profession2 1255
#define EDIT_a_account_modification_oldid1 1255
#define EDIT_a_account_inquire_grade2   1256
#define EDIT_a_account_modification_oldname 1256
#define EDIT_a_account_inquire_name3    1257
#define EDIT_a_account_modification_oldsex 1257
#define EDIT_a_account_inquire_sex3     1258
#define EDIT_a_account_modification_oldnation 1258
#define EDIT_a_account_modification_oldface 1259
#define EDIT_a_account_inquire_face3    1260
#define EDIT_a_account_modification_oldbirth 1260
#define EDIT_a_account_modification_oldtime 1261
#define EDIT_a_account_modification_oldcollege 1262
#define EDIT_a_account_inquire_unit3    1263
#define EDIT_a_account_inquire_college3 1263
#define EDIT_a_account_modification_oldprofession 1263
#define EDIT_a_account_inquire_profession3 1264
#define EDIT_a_account_modification_oldgrade 1264
#define EDIT_a_account_inquire_grade3   1265
#define EDIT_a_account_modification_newid 1265
#define EDIT_a_account_inquire_name4    1266
#define EDIT_a_account_modification_newname 1266
#define EDIT_a_account_inquire_sex4     1267
#define EDIT_a_account_modification_newsex 1267
#define EDIT_a_account_modification_newnation 1268
#define EDIT_a_account_inquire_face4    1269
#define EDIT_a_account_modification_newface 1269
#define EDIT_a_account_modification_newbirth 1270
#define EDIT_a_account_modification_newtime 1271
#define EDIT_a_account_inquire_unit4    1272
#define EDIT_a_account_inquire_college4 1272
#define EDIT_a_account_modification_newcollege 1272
#define EDIT_a_account_inquire_profession4 1273
#define EDIT_a_account_modification_newprofession 1273
#define EDIT_a_account_inquire_grade4   1274
#define EDIT_a_account_modification_newgrade 1274
#define EDIT_a_account_inquire_name5    1275
#define BUTTON_a_account_modification_location 1275
#define EDIT_a_account_inquire_sex5     1276
#define BUTTON_a_account_modification_delete 1276
#define EDIT_a_account_inquire_face5    1278
#define EDIT_a_account_inquire_unit5    1281
#define EDIT_a_account_inquire_college5 1281
#define EDIT_a_account_inquire_profession5 1282
#define EDIT_a_account_inquire_grade5   1283
#define EDIT_a_account_inquire_name6    1284
#define EDIT_a_account_inquire_sex6     1285
#define EDIT_a_account_inquire_face6    1287
#define EDIT_a_account_inquire_unit6    1290
#define EDIT_a_account_inquire_college6 1290
#define EDIT_a_account_inquire_profession6 1291
#define EDIT_a_account_inquire_grade6   1292
#define EDIT_a_teacher_inquire_id1      1293
#define EDIT_a_teacher_inquire_id2      1294
#define EDIT_a_teacher_inquire_id3      1295
#define EDIT_a_teacher_inquire_id4      1296
#define EDIT_a_teacher_inquire_id5      1297
#define EDIT_a_teacher_inquire_id6      1298
#define EDIT_a_teacher_inquire_name1    1299
#define EDIT_a_teacher_inquire_name2    1300
#define EDIT_a_teacher_inquire_name3    1301
#define EDIT_a_teacher_inquire_name4    1302
#define EDIT_a_teacher_inquire_name5    1303
#define EDIT_a_teacher_inquire_name6    1304
#define EDIT_a_teacher_inquire_sex1     1305
#define EDIT_a_teacher_inquire_sex2     1306
#define EDIT_a_teacher_inquire_sex3     1307
#define EDIT_a_teacher_inquire_sex4     1308
#define EDIT_a_teacher_inquire_sex5     1309
#define EDIT_a_teacher_inquire_sex6     1310
#define EDIT_a_teacher_inquire_face1    1311
#define EDIT_a_teacher_inquire_face2    1312
#define EDIT_a_teacher_inquire_face3    1313
#define EDIT_a_teacher_inquire_face4    1314
#define EDIT_a_teacher_inquire_face5    1315
#define EDIT_a_teacher_inquire_face6    1316
#define EDIT_a_teacher_inquire_college1 1317
#define EDIT_a_teacher_inquire_college2 1318
#define EDIT_a_teacher_inquire_college3 1319
#define EDIT_a_teacher_inquire_college4 1320
#define EDIT_a_teacher_inquire_college5 1321
#define EDIT_a_teacher_inquire_college6 1322
#define EDIT_a_teacher_inquire_profession1 1323
#define EDIT_a_teacher_inquire_profession2 1324
#define EDIT_a_teacher_inquire_profession3 1325
#define EDIT_a_teacher_inquire_profession4 1326
#define EDIT_a_teacher_inquire_profession5 1327
#define EDIT_a_teacher_inquire_profession6 1328
#define EDIT_a_teacher_inquire_grade1   1329
#define EDIT_a_teacher_inquire_grade2   1330
#define EDIT_a_teacher_inquire_grade3   1331
#define EDIT_a_teacher_inquire_grade4   1332
#define EDIT_a_teacher_inquire_grade5   1333
#define EDIT_a_teacher_inquire_grade6   1334
#define EDIT_a_teacher_inquire_page     1335
#define BUTTON_a_teacher_inquire_top    1336
#define BUTTON_a_teacher_inquire_prior  1337
#define BUTTON_a_teacher_inquire_next   1338
#define BUTTON_a_teacher_inquire_exit   1339
#define EDIT_a_teacher_modification_oldid 1340
#define EDIT_a_teacher_modification_oldid1 1341
#define EDIT_a_teacher_modification_oldname 1342
#define EDIT_a_teacher_modification_oldsex 1343
#define EDIT_a_teacher_modification_oldnation 1344
#define EDIT_a_teacher_modification_oldface 1345
#define EDIT_a_teacher_modification_oldbirth 1346
#define EDIT_a_teacher_modification_oldtime 1347
#define EDIT_a_teacher_modification_oldcollege 1348
#define EDIT_a_teacher_modification_oldprofession 1349
#define EDIT_a_teacher_modification_oldgrade 1350
#define EDIT_a_teacher_modification_newid 1351
#define EDIT_a_teacher_modification_newname 1352
#define EDIT_a_teacher_modification_newsex 1353
#define EDIT_a_teacher_modification_newnation 1354
#define EDIT_a_teacher_modification_newface 1355
#define EDIT_a_teacher_modification_newbirth 1356
#define EDIT_a_teacher_modification_newtime 1357
#define EDIT_a_teacher_modification_newcollege 1358
#define EDIT_a_teacher_modification_newprofession 1359
#define EDIT_a_teacher_modification_newgrade 1360
#define BUTTON_a_teacher_modification_location 1361
#define BUTTON_a_teacher_modification_add 1362
#define BUTTON_a_teacher_modification_affirm 1363
#define BUTTON_a_teacher_modification_delete 1364
#define BUTTON_a_teacher_modification_exit 1365
#define EDIT_a_student_inquire_id1      1366
#define EDIT_a_student_inquire_id2      1367
#define EDIT_a_student_inquire_id3      1368
#define EDIT_a_student_inquire_id4      1369
#define EDIT_a_student_inquire_id5      1370
#define EDIT_a_student_inquire_id6      1371
#define EDIT_a_student_inquire_name1    1372
#define EDIT_a_student_inquire_name2    1373
#define EDIT_a_student_inquire_name3    1374
#define EDIT_a_student_inquire_name4    1375
#define EDIT_a_student_inquire_name5    1376
#define EDIT_a_student_inquire_name6    1377
#define EDIT_a_student_inquire_sex1     1378
#define EDIT_a_student_inquire_sex2     1379
#define EDIT_a_student_inquire_sex3     1380
#define EDIT_a_student_inquire_sex4     1381
#define EDIT_a_student_inquire_sex5     1382
#define EDIT_a_student_inquire_sex6     1383
#define EDIT_a_student_inquire_face1    1384
#define EDIT_a_student_inquire_face2    1385
#define EDIT_a_student_inquire_face3    1386
#define EDIT_a_student_inquire_face4    1387
#define EDIT_a_student_inquire_face5    1388
#define EDIT_a_student_inquire_face6    1389
#define EDIT_a_student_inquire_college1 1390
#define EDIT_a_student_inquire_college2 1391
#define EDIT_a_student_inquire_college3 1392
#define EDIT_a_student_inquire_college4 1393
#define EDIT_a_student_inquire_college5 1394
#define EDIT_a_student_inquire_college6 1395
#define EDIT_a_student_inquire_profession1 1396
#define EDIT_a_student_inquire_profession2 1397
#define EDIT_a_student_inquire_profession3 1398
#define EDIT_a_student_inquire_profession4 1399
#define EDIT_a_student_inquire_profession5 1400
#define EDIT_a_student_inquire_profession6 1401
#define EDIT_a_student_inquire_grade1   1402
#define EDIT_a_student_inquire_grade2   1403
#define EDIT_a_student_inquire_grade3   1404
#define EDIT_a_student_inquire_grade4   1405
#define EDIT_a_student_inquire_grade5   1406
#define EDIT_a_student_inquire_grade6   1407
#define EDIT_a_student_inquire_page     1408
#define BUTTON_a_student_inquire_top    1409
#define BUTTON_a_student_inquire_prior  1411
#define BUTTON_a_student_inquire_next   1412
#define BUTTON_a_student_inquire_exit   1413
#define EDIT_a_student_modification_oldid 1414
#define EDIT_a_student_modification_oldid1 1415
#define EDIT_a_student_modification_oldname 1416
#define EDIT_a_student_modification_oldsex 1417
#define EDIT_a_student_modification_oldnation 1418
#define EDIT_a_student_modification_oldface 1419
#define EDIT_a_student_modification_oldbirth 1420
#define EDIT_a_student_modification_oldtime 1421
#define EDIT_a_student_modification_oldcollege 1422
#define EDIT_a_student_modification_oldprofession 1423
#define EDIT_a_student_modification_oldgrade 1424
#define EDIT_a_student_modification_newid 1425
#define EDIT_a_student_modification_newname 1426
#define EDIT_a_student_modification_newsex 1427
#define EDIT_a_student_modification_newnation 1428
#define EDIT_a_student_modification_newface 1429
#define EDIT_a_student_modification_newbirth 1430
#define EDIT_a_student_modification_newtime 1431
#define EDIT_a_student_modification_newcollege 1432
#define EDIT_a_student_modification_newprofession 1433
#define EDIT_a_student_modification_newgrade 1434
#define BUTTON_a_student_modification_location 1435
#define BUTTON_a_student_modification_add 1436
#define BUTTON_a_student_modification_affirm 1437
#define BUTTON_a_student_modification_delete 1438
#define BUTTON_a_student_modification_exit 1439
#define EDIT_a_score_inquire_name1      1446
#define EDIT_a_score_inquire_id1        1447
#define EDIT_a_score_inquire_subject1   1448
#define EDIT_a_score_inquire_grade1     1449
#define EDIT_a_score_inquire_paper_score1 1450
#define EDIT_a_score_inquire_usual_score1 1451
#define EDIT_a_score_inquire_makeup_score1 1452
#define EDIT_a_score_inquire_score1     1453
#define EDIT_a_score_inquire_name2      1454
#define EDIT_a_score_inquire_id2        1455
#define EDIT_a_score_inquire_subject2   1456
#define EDIT_a_score_inquire_grade2     1457
#define EDIT_a_score_inquire_paper_score2 1458
#define EDIT_a_score_inquire_usual_score2 1459
#define EDIT_a_score_inquire_makeup_score2 1460
#define EDIT_a_score_inquire_score2     1461
#define EDIT_a_score_inquire_name3      1462
#define EDIT_a_score_inquire_id3        1463
#define EDIT_a_score_inquire_subject3   1464
#define EDIT_a_score_inquire_grade3     1465
#define EDIT_a_score_inquire_paper_score3 1466
#define EDIT_a_score_inquire_usual_score3 1467
#define EDIT_a_score_inquire_makeup_score3 1468
#define EDIT_a_score_inquire_score3     1469
#define EDIT_a_score_inquire_name4      1470
#define EDIT_a_score_inquire_id4        1471
#define EDIT_a_score_inquire_subject4   1472
#define EDIT_a_score_inquire_grade4     1473
#define EDIT_a_score_inquire_paper_score4 1474
#define EDIT_a_score_inquire_usual_score4 1475
#define EDIT_a_score_inquire_makeup_score4 1476
#define EDIT_a_score_inquire_score4     1477
#define EDIT_a_score_inquire_name5      1478
#define EDIT_a_score_inquire_id5        1479
#define EDIT_a_score_inquire_subject5   1480
#define EDIT_a_score_inquire_grade5     1481
#define EDIT_a_score_inquire_paper_score5 1482
#define EDIT_a_score_inquire_usual_score5 1483
#define EDIT_a_score_inquire_makeup_score5 1484
#define EDIT_a_score_inquire_score5     1485
#define EDIT_a_score_inquire_name6      1486
#define EDIT_a_score_inquire_id6        1487
#define EDIT_a_score_inquire_subject6   1488
#define EDIT_a_score_inquire_grade6     1489
#define EDIT_a_score_inquire_paper_score6 1490
#define EDIT_a_score_inquire_usual_score6 1491
#define EDIT_a_score_inquire_makeup_score6 1492
#define EDIT_a_score_inquire_score6     1493
#define EDIT_a_score_inquire_page       1494
#define BUTTON_a_score_inquire_top      1495
#define BUTTON_a_score_inquire_prior    1496
#define BUTTON_a_score_inquire_next     1497
#define EDIT_a_score_modification_oldid 1497
#define BUTTON_a_score_inquire_exit     1498
#define BUTTON_a_score_modification_location 1499
#define EDIT_a_score_self_inquire_id    1499
#define EDIT_a_score_modification_oldname 1500
#define EDIT_a_score_modification_oldcollege 1501
#define EDIT_a_score_modification_oldprofession 1502
#define EDIT_a_score_modification_oldgrade 1503
#define EDIT_a_score_modification_oldterm 1504
#define EDIT_a_score_modification_oldsubject 1505
#define EDIT_a_score_modification_oldpaper_score 1506
#define BUTTON_a_score_modification_affirm 1507
#define EDIT_a_score_modification_oldusual_score 1508
#define EDIT_a_score_modification_oldmakeup_score 1509
#define EDIT_a_score_modification_oldscore 1510
#define EDIT_a_score_modification_newid 1511
#define EDIT_a_score_modification_newname 1512
#define EDIT_a_score_modification_newcollege 1513
#define EDIT_a_score_modification_newprofession 1514
#define EDIT_a_score_modification_newgrade 1515
#define EDIT_a_score_modification_newterm 1516
#define EDIT_a_score_modification_newsubject 1517
#define EDIT_a_score_modification_newpaper_score 1518
#define EDIT_a_score_modification_newusual_score 1519
#define EDIT_a_score_modification_newmakeup_score 1520
#define EDIT_a_score_modification_newscore 1521
#define BUTTON_a_score_modification_delete 1522
#define BUTTON_a_score_modification_exit 1523
#define EDIT_a_score_inquire_term1      1524
#define EDIT_a_score_inquire_term2      1525
#define EDIT_a_score_inquire_term3      1526
#define EDIT_a_score_inquire_term4      1527
#define EDIT_a_score_inquire_term5      1528
#define EDIT_a_score_inquire_term6      1529
#define EDIT_a_score_self_inquire_name1 1530
#define EDIT_a_score_self_inquire_name2 1531
#define EDIT_a_score_self_inquire_name3 1532
#define EDIT_a_score_self_inquire_name4 1533
#define EDIT_a_score_self_inquire_name5 1534
#define EDIT_a_score_self_inquire_name6 1535
#define EDIT_a_score_self_inquire_id1   1536
#define EDIT_a_score_self_inquire_id2   1537
#define EDIT_a_score_self_inquire_id3   1538
#define EDIT_a_score_self_inquire_id4   1539
#define EDIT_a_score_self_inquire_id5   1540
#define EDIT_a_score_self_inquire_id6   1541
#define EDIT_a_score_self_inquire_grade1 1542
#define EDIT_a_score_self_inquire_grade2 1543
#define EDIT_a_score_self_inquire_grade3 1544
#define EDIT_a_score_self_inquire_term1 1545
#define EDIT_a_score_self_inquire_subject1 1546
#define EDIT_a_score_self_inquire_paper_score1 1547
#define EDIT_a_score_self_inquire_usual_score1 1548
#define EDIT_a_score_self_inquire_makeup_score1 1549
#define EDIT_a_score_self_inquire_score1 1550
#define EDIT_a_score_self_inquire_subject2 1551
#define EDIT_a_score_self_inquire_paper_score2 1552
#define EDIT_a_score_self_inquire_usual_score2 1553
#define EDIT_a_score_self_inquire_makeup_score2 1554
#define EDIT_a_score_self_inquire_score2 1555
#define EDIT_a_score_self_inquire_term2 1556
#define EDIT_a_score_self_inquire_subject3 1557
#define EDIT_a_score_self_inquire_paper_score3 1558
#define EDIT_a_score_self_inquire_usual_score3 1559
#define EDIT_a_score_self_inquire_makeup_score3 1560
#define EDIT_a_score_self_inquire_score3 1561
#define EDIT_a_score_self_inquire_term3 1562
#define EDIT_a_score_self_inquire_subject4 1563
#define EDIT_a_score_self_inquire_grade4 1564
#define EDIT_a_score_self_inquire_paper_score4 1565
#define EDIT_a_score_self_inquire_usual_score4 1566
#define EDIT_a_score_self_inquire_makeup_score4 1567
#define EDIT_a_score_self_inquire_score4 1568
#define EDIT_a_score_self_inquire_term4 1569
#define EDIT_a_score_self_inquire_subject5 1570
#define EDIT_a_score_self_inquire_grade5 1571
#define EDIT_a_score_self_inquire_paper_score5 1572
#define EDIT_a_score_self_inquire_usual_score5 1573
#define EDIT_a_score_self_inquire_makeup_score5 1574
#define EDIT_a_score_self_inquire_score5 1575
#define EDIT_a_score_self_inquire_term5 1576
#define EDIT_a_score_self_inquire_subject6 1577
#define EDIT_a_score_self_inquire_grade6 1578
#define EDIT_a_score_self_inquire_paper_score6 1579
#define EDIT_a_score_self_inquire_usual_score6 1580
#define EDIT_a_score_self_inquire_makeup_score6 1581
#define EDIT_a_score_self_inquire_score6 1582
#define EDIT_a_score_self_inquire_term6 1583
#define BUTTON_a_score_self_inquire_top 1584
#define BUTTON_a_score_self_inquire_prior 1585
#define BUTTON_a_score_self_inquire_next 1586
#define BUTTON_a_score_self_inquire_exit 1587
#define EDIT_a_score_self_inquire_page  1588
#define EDIT_a_score_term_inquire_grade 1589
#define EDIT_a_score_term_inquire_name1 1590
#define EDIT_a_score_term_inquire_id1   1591
#define EDIT_a_score_term_inquire_grade1 1592
#define EDIT_a_score_term_inquire_term1 1593
#define EDIT_a_score_term_inquire_subject1 1594
#define EDIT_a_score_term_inquire_paper_score1 1595
#define EDIT_a_score_term_inquire_usual_score1 1596
#define EDIT_a_score_term_inquire_makeup_score1 1597
#define EDIT_a_score_term_inquire_score1 1598
#define EDIT_a_score_term_inquire_name2 1599
#define EDIT_a_score_term_inquire_id2   1600
#define EDIT_a_score_term_inquire_subject2 1601
#define EDIT_a_score_term_inquire_grade2 1602
#define EDIT_a_score_term_inquire_paper_score2 1603
#define EDIT_a_score_term_inquire_usual_score2 1604
#define EDIT_a_score_term_inquire_makeup_score2 1605
#define EDIT_a_score_term_inquire_score2 1606
#define EDIT_a_score_term_inquire_term2 1607
#define EDIT_a_score_term_inquire_name3 1608
#define EDIT_a_score_term_inquire_id3   1609
#define EDIT_a_score_term_inquire_subject3 1610
#define EDIT_a_score_term_inquire_grade3 1611
#define EDIT_a_score_term_inquire_paper_score3 1612
#define EDIT_a_score_term_inquire_usual_score3 1613
#define EDIT_a_score_term_inquire_makeup_score3 1614
#define EDIT_a_score_term_inquire_score3 1615
#define EDIT_a_score_term_inquire_term3 1616
#define EDIT_a_score_term_inquire_name4 1617
#define EDIT_a_score_term_inquire_id4   1618
#define EDIT_a_score_term_inquire_subject4 1619
#define EDIT_a_score_term_inquire_grade4 1620
#define EDIT_a_score_term_inquire_paper_score4 1621
#define EDIT_a_score_term_inquire_usual_score4 1622
#define EDIT_a_score_term_inquire_makeup_score4 1623
#define EDIT_a_score_term_inquire_score4 1624
#define EDIT_a_score_term_inquire_term4 1625
#define EDIT_a_score_term_inquire_name5 1626
#define EDIT_a_score_term_inquire_id5   1627
#define EDIT_a_score_term_inquire_subject5 1628
#define EDIT_a_score_term_inquire_grade5 1629
#define EDIT_a_score_term_inquire_paper_score5 1630
#define EDIT_a_score_term_inquire_usual_score5 1631
#define EDIT_a_score_term_inquire_makeup_score5 1632
#define EDIT_a_score_term_inquire_score5 1633
#define EDIT_a_score_term_inquire_term5 1634
#define EDIT_a_score_term_inquire_name6 1635
#define EDIT_a_score_term_inquire_id6   1636
#define EDIT_a_score_term_inquire_subject6 1637
#define EDIT_a_score_term_inquire_grade6 1638
#define EDIT_a_score_term_inquire_paper_score6 1639
#define EDIT_a_score_term_inquire_usual_score6 1640
#define EDIT_a_score_term_inquire_makeup_score6 1641
#define EDIT_a_score_term_inquire_score6 1642
#define EDIT_a_score_term_inquire_term6 1643
#define EDIT_a_score_term_inquire_page  1644
#define BUTTON_a_score_term_inquire_top 1645
#define BUTTON_a_score_term_inquire_prior 1647
#define BUTTON_a_score_term_inquire_next 1648
#define BUTTON_a_score_term_inquire_exit 1649
#define BUTTON_a_score_enter_location   1655
#define BUTTON_a_score_enter_affirm     1656
#define BUTTON_a_score_enter_exit       1657
#define EDIT_a_score_enter_name1        1658
#define EDIT_a_score_enter_id1          1659
#define EDIT_a_score_enter_paper_score1 1660
#define EDIT_a_score_enter_usual_score1 1661
#define EDIT_a_score_enter_makeup_score1 1662
#define EDIT_a_score_enter_score1       1663
#define EDIT_a_score_enter_name2        1664
#define EDIT_a_score_enter_id2          1665
#define EDIT_a_score_enter_paper_score2 1666
#define EDIT_a_score_enter_usual_score2 1667
#define EDIT_a_score_enter_makeup_score2 1668
#define EDIT_a_score_enter_score2       1669
#define EDIT_a_score_enter_name3        1670
#define EDIT_a_score_enter_id3          1671
#define EDIT_a_score_enter_paper_score3 1672
#define EDIT_a_score_enter_usual_score3 1673
#define EDIT_a_score_enter_makeup_score3 1674
#define EDIT_a_score_enter_score3       1675
#define EDIT_a_score_enter_name4        1676
#define EDIT_a_score_enter_id4          1677
#define EDIT_a_score_enter_paper_score4 1678
#define EDIT_a_score_enter_usual_score4 1679
#define EDIT_a_score_enter_makeup_score4 1680
#define EDIT_a_score_enter_score4       1681
#define EDIT_a_score_enter_name5        1682
#define EDIT_a_score_enter_id5          1683
#define EDIT_a_score_enter_paper_score5 1684
#define EDIT_a_score_enter_usual_score5 1685
#define EDIT_a_score_enter_makeup_score5 1686
#define EDIT_a_score_enter_score5       1687
#define EDIT_a_score_enter_name6        1688
#define EDIT_a_score_enter_id6          1689
#define EDIT_a_score_enter_paper_score6 1690
#define EDIT_a_score_enter_usual_score6 1691
#define EDIT_a_score_enter_makeup_score6 1692
#define EDIT_a_score_enter_score6       1693
#define EDIT_a_score_enter_subject      1694
#define EDIT_a_score_enter_grade        1695
#define EDIT_a_score_enter_term         1696
#define EDIT_a_score_enter_page         1697
#define EDIT_a_score_analyse_sum_score  1698
#define EDIT_a_score_analyse_sum_gread  1699
#define BUTTON_a_score_analyse_sum_enter 1700
#define BUTTON_a_score_analyse_sum_exit 1701
#define EDIT_a_score_analyse_average_gread 1702
#define EDIT_a_score_analyse_average_score 1703
#define BUTTON_a_score_analyse_average_enter 1704
#define BUTTON_a_score_analyse_average_exit 1705
#define s_account_inquire               32771
#define s_account_password              32772
#define s_account_modification          32773
#define s_college_college               32775
#define s_college_department            32776
#define s_college_class                 32777
#define s_teacher                       32778
#define s_teacher_inquire               32778
#define s_course_college                32779
#define s_course_profession             32780
#define s_myself_info                   32781
#define s_myself_class                  32782
#define t_score_add                     32785
#define t_score_self_inquire            32785
#define t_score_modification            32786
#define t_score_analyse                 32787
#define t_account_inquire               32788
#define t_account_password              32789
#define t_account_modification          32790
#define t_college_college               32791
#define t_college_department            32792
#define t_college_inquire               32792
#define t_college_class                 32793
#define t_college_modification          32793
#define t_teacher                       32794
#define t_teacher_inquire               32794
#define t_course_college                32795
#define t_course_inquire                32795
#define t_course_profession             32796
#define t_myself_info                   32797
#define t_myself_class                  32798
#define help_about                      32799
#define help_exit                       32800
#define a_self_inquire                  32801
#define a_account_password              32802
#define a_self_password                 32802
#define a_account_modification          32803
#define a_college_college               32804
#define a_college_department            32805
#define a_college_inquire               32805
#define a_college_class                 32806
#define a_course_college                32808
#define a_course_profession             32809
#define a_myself_info                   32810
#define a_myself_class                  32811
#define a_score_add                     32812
#define a_score_self_inquire            32812
#define a_score_modification            32813
#define a_score_analyse                 32814
#define a_college_modification          32815
#define a_teacher_inquire               32818
#define a_teacher_modification          32819
#define a_course_modification           32820
#define a_course_make                   32821
#define a_student_modification          32822
#define a_student_inquire               32823
#define t_student_inquire               32824
#define a_course_info                   32826
#define a_course_inquire                32826
#define a_course_plan_inquire           32827
#define a_course_plan_modification      32828
#define a_score_team_inquire            32829
#define a_score_term_inquire            32829
#define a_score_enter                   32835
#define a_score_analyse_sum             32836
#define a_score_analyse_average         32837
#define a_score_analyse_fail            32838
#define a_account_inquire1              32840
#define a_account_inquire               32840
#define a_profession_inquire            32842
#define a_profession_modification       32843
#define a_class_inquire                 32844
#define a_class_modification            32845
#define t_score_team_inquire            32846
#define t_score_enter                   32847
#define t_score_analyse_sum             32848
#define t_score_analyse_fail            32849
#define s_college_inquire               32850
#define s_course_inquire                32851
#define s_score_self_inquire            32852
#define s_class_inquire                 32853
#define t_class_inquire                 32854
#define a_score_inquire                 32855
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1706
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
